# Generated by Django 3.2.4 on 2022-01-10 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_slug', models.SlugField(default=False, null=True)),
                ('category_img', models.ImageField(upload_to='category_image')),
                ('category_discription', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slideimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideName', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='Slideimages')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('product_image1', models.ImageField(upload_to='product_image')),
                ('product_name', models.CharField(max_length=200)),
                ('prices', models.FloatField(default=0.0)),
                ('product_discriptions', models.TextField(max_length=100)),
                ('Condition', models.CharField(choices=[('N', 'New'), ('ULN', 'Used-like New'), ('NG', 'New-Good'), ('UF', 'Used-Fair')], default='New', max_length=40)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('facebook_userName', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp_number', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dagracemarketapp.category')),
            ],
        ),
    ]
