# Generated by Django 3.2.4 on 2022-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagracemarketapp', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-14 12:00'),
            preserve_default=False,
        ),
    ]
