# Generated by Django 3.2.4 on 2022-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagracemarketapp', '0006_remove_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
